version: '3.9'

services:

  api:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    environment:
      spring.datasource.url: jdbc:mysql://db:3306/WONGSITO?serverTimezone=UTC
      spring.datasource.username: root
      spring.datasource.password: root
      spring.jpa.database-platform: org.hibernate.dialect.MySQL8Dialect
      spring.sql.init.mode: always
      spring.jpa.hibernate.ddl-auto: create
      server.port: 8090
    depends_on:
      - db

  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: WONGSITO
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
