version: '3.9'

services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    command: ["./wait-for-it.sh", "db:3306", "--", "java", "-jar", "/app.jar"]
    environment:
      spring.datasource.url: jdbc:mysql://db:3306/WONGSITO?serverTimezone=UTC
      spring.datasource.username: root
      spring.datasource.password: root
      spring.jpa.database-platform: org.hibernate.dialect.MySQL8Dialect
      spring.sql.init.mode: always
      spring.jpa.hibernate.ddl-auto: create
      server.port: 8090

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: WONGSITO
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
