version: '3.9'

services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    depends_on:
      - db
    networks:
      - mi-red
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: WONGSITO
      MYSQL_ROOT_PASSWORD: root
    hostname: db
    networks:
      - mi-red

networks:
  mi-red:
    driver: bridge
