version: '3.9'

services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    depends_on:
      - db
    networks:
      - mi-red
    command: bash -c "mvn verify sonar:sonar -Dsonar.projectKey=sitili_back -Dsonar.projectName='sitili_back' -Dsonar.host.url=http://3.219.197.64:9000 -Dsonar.token=sqp_d0a12bb474391abd9d325b6f1bf65ad10ca79efb"
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: WONGSITO
      MYSQL_ROOT_PASSWORD: root
    hostname: db
    networks:
      - mi-red

networks:
  mi-red:
    driver: bridge
